apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mutuelle

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - hpa.yaml
  - pdb.yaml

labels:
  - pairs:
      app: mutuelle-rag-agent
      app.kubernetes.io/name: mutuelle-rag-agent
      app.kubernetes.io/component: backend
